#!/usr/bin/env python3
"""
Generate a developer-friendly PDF report for Patch Agent outputs.
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Preformatted,
)

from .metrics import load_records, summarize


def _section_header(text: str, styles) -> Paragraph:
    return Paragraph(f"<b>{text}</b>", styles["Heading3"])


def _quality_table(metrics: Dict) -> Table:
    data = [
        ["Quality Score", metrics.get("score")],
        ["Unsafe call removed", metrics.get("unsafe_removed")],
        ["Safe helper added", metrics.get("safe_added")],
        ["Bounds check added", metrics.get("bounds_check_added")],
        ["Added conditions", metrics.get("added_conditions")],
        ["Lines added", metrics.get("added_lines")],
        ["Lines deleted", metrics.get("deleted_lines")],
    ]
    table = Table(data, colWidths=[160, 200])
    table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ]
        )
    )
    return table


def build_report(records: List[Dict], dest: Path) -> None:
    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    mono = ParagraphStyle(
        "Code",
        parent=styles["Code"],
        fontName="Courier",
        fontSize=9,
        leading=11,
    )

    story = []
    metrics_summary = summarize(records)

    story.append(Paragraph("Patch Agent Report", styles["Title"]))
    story.append(Spacer(1, 12))
    story.append(
        Paragraph(
            "This document summarizes the RCA-driven patches generated by the Patch Agent.",
            body,
        )
    )
    story.append(Spacer(1, 18))

    # Executive Summary Section
    story.append(Paragraph("Executive Summary", styles["Heading1"]))
    story.append(Spacer(1, 6))

    # Success Rate and Overview
    total = metrics_summary.get("total_records", 0)
    success_rate = metrics_summary.get("success_rate", 0.0)
    valid_patches = metrics_summary.get("valid_patches", 0)

    overview_data = [
        ["Total Records Processed", str(total)],
        ["Valid Patches Generated", str(valid_patches)],
        ["Success Rate", f"{success_rate}%"],
        ["Average Quality Score", str(metrics_summary.get("avg_quality_score", "N/A"))],
        ["Median Quality Score", str(metrics_summary.get("median_quality_score", "N/A"))],
    ]

    overview_table = Table(overview_data, colWidths=[200, 180])
    overview_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightblue),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    story.append(overview_table)
    story.append(Spacer(1, 12))

    # Quality Distribution
    quality_dist = metrics_summary.get("quality_distribution", {})
    if quality_dist:
        story.append(Paragraph("Quality Distribution", styles["Heading3"]))
        quality_data = [
            ["Quality Tier", "Count"],
            ["High Quality (≥0.8)", str(quality_dist.get("high_quality (≥0.8)", 0))],
            ["Medium Quality (0.5-0.8)", str(quality_dist.get("medium_quality (0.5-0.8)", 0))],
            ["Low Quality (<0.5)", str(quality_dist.get("low_quality (<0.5)", 0))],
        ]
        quality_table = Table(quality_data, colWidths=[200, 180])
        quality_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ]
            )
        )
        story.append(quality_table)
        story.append(Spacer(1, 12))

    # Security Improvements
    sec_improvements = metrics_summary.get("security_improvements", {})
    if sec_improvements:
        story.append(Paragraph("Security Improvements", styles["Heading3"]))
        sec_data = [
            ["Improvement Type", "Count"],
            ["Bounds Checks Added", str(sec_improvements.get("bounds_checks_added", 0))],
            ["Unsafe Calls Removed", str(sec_improvements.get("unsafe_calls_removed", 0))],
            ["Safe Alternatives Added", str(sec_improvements.get("safe_alternatives_added", 0))],
            ["Complete Secure Replacements", str(metrics_summary.get("secure_replacements", 0))],
        ]
        sec_table = Table(sec_data, colWidths=[200, 180])
        sec_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgreen),
                ]
            )
        )
        story.append(sec_table)
        story.append(Spacer(1, 12))

    # Failure Modes
    failure_modes = metrics_summary.get("failure_modes")
    if failure_modes:
        story.append(Paragraph("Failure Modes", styles["Heading3"]))
        failure_data = [["Failure Type", "Count"]]
        for mode, count in sorted(failure_modes.items(), key=lambda x: x[1], reverse=True):
            failure_data.append([mode, str(count)])
        failure_table = Table(failure_data, colWidths=[200, 180])
        failure_table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightcoral),
                ]
            )
        )
        story.append(failure_table)
        story.append(Spacer(1, 12))

    # Code Statistics
    story.append(Paragraph("Code Statistics", styles["Heading3"]))
    code_stats_data = [
        ["Metric", "Value"],
        ["Average Lines Added", str(metrics_summary.get("avg_added_lines", 0))],
        ["Average Lines Deleted", str(metrics_summary.get("avg_deleted_lines", 0))],
    ]
    code_stats_table = Table(code_stats_data, colWidths=[200, 180])
    code_stats_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ]
        )
    )
    story.append(code_stats_table)
    story.append(Spacer(1, 18))

    # Individual Patches Section
    story.append(Paragraph("Individual Patches", styles["Heading1"]))
    story.append(Spacer(1, 12))

    for idx, rec in enumerate(records, start=1):
        story.append(Paragraph(f"Patch {idx}: {rec.get('func_name', 'N/A')}", styles["Heading2"]))
        story.append(
            Paragraph(
                f"<b>Repository:</b> {rec.get('repo_name')} &nbsp;&nbsp; "
                f"<b>File:</b> {rec.get('file_path')}",
                body,
            )
        )
        story.append(
            Paragraph(f"<b>Commit Context:</b> {rec.get('commit_msg', '(missing)')}", body)
        )
        story.append(Spacer(1, 6))

        story.append(_section_header("Root Cause Analysis", styles))
        story.append(Paragraph(rec.get("rca_generated", "(missing)"), body))
        story.append(Spacer(1, 6))

        story.append(_section_header("Generated Patch", styles))
        story.append(Preformatted(rec.get("patch_generated", ""), mono))
        story.append(Spacer(1, 6))

        story.append(_section_header("Patch Rationale", styles))
        story.append(Paragraph(rec.get("patch_rationale", ""), body))
        story.append(Spacer(1, 6))

        story.append(_section_header("Diff Summary", styles))
        story.append(Preformatted(rec.get("patch_diff", ""), mono))
        story.append(Spacer(1, 6))

        qm = rec.get("quality_metrics") or {}
        story.append(_section_header("Quality Metrics", styles))
        story.append(_quality_table(qm))
        story.append(Spacer(1, 12))

        retrieved = rec.get("retrieved_examples") or []
        if retrieved:
            story.append(_section_header("Retrieved Reference Examples", styles))
            for ex in retrieved:
                story.append(
                    Paragraph(
                        f"<b>Commit:</b> {ex.get('commit_msg', '(missing)')}", body
                    )
                )
                story.append(
                    Paragraph(
                        f"<b>Score:</b> {round(ex.get('score', 0.0), 3)}", body
                    )
                )
                story.append(Spacer(1, 4))
            story.append(Spacer(1, 8))

    doc = SimpleDocTemplate(
        str(dest),
        pagesize=LETTER,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )
    doc.build(story)


def main():
    parser = argparse.ArgumentParser(description="Generate PDF report from patch outputs.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("patch_agent/outputs/patch_megavul_generated.jsonl"),
        help="Patch Agent JSONL output file.",
    )
    parser.add_argument(
        "--session",
        type=Path,
        help="Optional JSON file produced in the same run containing only the current patches.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("patch_agent/outputs/patch_report.pdf"),
        help="Destination PDF path.",
    )
    args = parser.parse_args()

    # Auto-detect session file if not explicitly provided
    input_file = args.input
    if not args.session:
        session_file = input_file.parent / f"{input_file.stem}.session.jsonl"
        if session_file.exists():
            input_file = session_file
            print(f"📄 Using session file: {session_file}")
    else:
        input_file = args.session

    records = load_records(input_file)
    if not records:
        raise SystemExit("No records found in input file.")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    build_report(records, args.output)
    print(f"✅ Report written to {args.output}")


if __name__ == "__main__":
    main()

